apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: us.gcr.io/servicedesk-dev-361311/category 
          env:
            - name: MONGO_URI
              value: 'mongodb://category-mongo-service:27017/category'
            - name: NATS_CLUSTER_ID
              value: 'service-desk'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  selector:
    app: category
  ports:
    - name: category
      protocol: TCP
      port: 5002
      targetPort: 5002