apiVersion: apps/v1
kind: Deployment
metadata:
  name: escalation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: escalation
  template:
    metadata:
      labels:
        app: escalation
    spec:
      containers:
        - name: escalation
          image: us.gcr.io/servicedesk-dev-361311/escalation 
          env:
            - name: MONGO_URI
              value: 'mongodb://escalation-mongo-service:27017/escalation'
            - name: NATS_CLUSTER_ID
              value: 'service-desk'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: escalation-service
spec:
  selector:
    app: escalation
  ports:
    - name: escalation
      protocol: TCP
      port: 5004
      targetPort: 5004