apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group
  template:
    metadata:
      labels:
        app: group
    spec:
      containers:
        - name: group
          image: us.gcr.io/servicedesk-dev-361311/group 
          env:
            - name: MONGO_URI
              value: 'mongodb://group-mongo-service:27017/group'
            - name: NATS_CLUSTER_ID
              value: 'tasks'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: 'http://nats-service:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 

---

apiVersion: v1
kind: Service
metadata:
  name: group-service
spec:
  selector:
    app: group
  ports:
    - name: group
      protocol: TCP
      port: 5001
      targetPort: 5001